version: '3.8'

services:
  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=myappdb
    networks:
      - myapp-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myappdb
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db-data:

